[package]
name = "snk-capture"
version = "0.0.1"
links = "snk-capture"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[build-dependencies]
tauri-plugin = { workspace = true }

[dependencies]
snk-library = { path = "../snk-library" }
tauri.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
xcap.workspace = true
image.workspace = true
uuid.workspace = true
anyhow.workspace = true

[dev-dependencies]
serde_json = { workspace = true }
tempfile = "3"
