//! macOS native implementations: NSPasteboard for clipboard flag
//! inspection, NSWorkspace for the frontmost-app source.

use objc2::rc::Retained;
use objc2_app_kit::{NSPasteboard, NSRunningApplication, NSWorkspace};
use objc2_foundation::NSString;

use crate::source_app::SourceApp;

const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

pub(crate) fn is_sensitive() -> bool {
    let pasteboard: Retained<NSPasteboard> = NSPasteboard::generalPasteboard();
    let Some(types) = pasteboard.types() else {
        return false;
    };
    for i in 0..types.len() {
        // NSPasteboardType is a typed newtype around NSString; the
        // Deref/AsRef impls let us treat it as &NSString for to_string().
        let t = types.objectAtIndex(i);
        let s: &NSString = &t;
        let s = s.to_string();
        if CONCEALED_TYPES.contains(&s.as_str()) {
            return true;
        }
    }
    false
}

pub(crate) fn current_source_app() -> Option<SourceApp> {
    let workspace: Retained<NSWorkspace> = NSWorkspace::sharedWorkspace();
    let app: Retained<NSRunningApplication> = workspace.frontmostApplication()?;

    let bundle_id: String = app.bundleIdentifier()?.to_string();
    let display_name: String = app
        .localizedName()
        .map(|s| s.to_string())
        .unwrap_or_else(|| bundle_id.clone());

    Some(SourceApp {
        identifier: bundle_id,
        display_name,
        kind: crate::source_app::SourceAppKind::MacosBundleId,
    })
}
