//! macOS native implementations: NSPasteboard for clipboard flag
//! inspection, NSWorkspace for the frontmost-app source.

use objc2::rc::Retained;
use objc2_app_kit::{NSPasteboard, NSRunningApplication, NSWorkspace};
use objc2_foundation::NSString;

use crate::source_app::SourceApp;

const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

pub(crate) fn is_sensitive() -> bool {
    // SAFETY: NSPasteboard generalPasteboard is a thread-safe singleton
    // accessor; objc2-app-kit's binding is `unsafe` because it crosses
    // the Objective-C boundary but the call itself has no preconditions.
    let pasteboard: Retained<NSPasteboard> = unsafe { NSPasteboard::generalPasteboard() };
    // types() returns Option<Retained<NSArray<NSPasteboardType>>> in
    // objc2-app-kit 0.3 — None == nothing on the pasteboard right now,
    // which we treat as "not sensitive" (nothing to leak).
    let Some(types) = (unsafe { pasteboard.types() }) else {
        return false;
    };
    for i in 0..types.len() {
        // NSPasteboardType is a typed newtype around NSString; the
        // Deref/AsRef impls let us treat it as &NSString for to_string().
        let t = types.objectAtIndex(i);
        let s: &NSString = &t;
        let s = s.to_string();
        if CONCEALED_TYPES.iter().any(|c| *c == s.as_str()) {
            return true;
        }
    }
    false
}

pub(crate) fn current_source_app() -> Option<SourceApp> {
    // SAFETY: NSWorkspace::sharedWorkspace and frontmostApplication are
    // thread-safe Cocoa singletons. The returned NSRunningApplication may
    // be nil (returned as Option) during fast app switches.
    let workspace: Retained<NSWorkspace> = unsafe { NSWorkspace::sharedWorkspace() };
    let app: Retained<NSRunningApplication> = unsafe { workspace.frontmostApplication() }?;

    let bundle_id: String = unsafe { app.bundleIdentifier() }?.to_string();
    let display_name: String = unsafe { app.localizedName() }
        .map(|s| s.to_string())
        .unwrap_or_else(|| bundle_id.clone());

    Some(SourceApp {
        identifier: bundle_id,
        display_name,
        kind: crate::source_app::SourceAppKind::MacosBundleId,
    })
}
