[package]
name = "snapper-keeper-app"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "protocol-asset"] }
tauri-plugin-global-shortcut.workspace = true
tauri-plugin-updater.workspace = true
snk-library = { path = "../../crates/snk-library" }
snk-hotkeys = { path = "../../crates/snk-hotkeys" }
snk-capture = { path = "../../crates/snk-capture" }
snk-annotate = { path = "../../crates/snk-annotate" }
snk-clipboard = { path = "../../crates/snk-clipboard" }
snk-ocr = { path = "../../crates/snk-ocr" }
snk-updater = { path = "../../crates/snk-updater" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
